#!/usr/bin/env bash
# =============================================================================
# PumpFun — All-in-one VPS Deploy Script
# =============================================================================
# Tested on Ubuntu 22.04 LTS.
# Idempotent: safe to re-run for updates.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/Ghost69-321/PumpFun/main/scripts/deploy.sh | bash
#   — or —
#   chmod +x scripts/deploy.sh && sudo ./scripts/deploy.sh
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Color helpers
# ---------------------------------------------------------------------------
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
section() { echo -e "\n${GREEN}==============================${NC}"; echo -e "${GREEN}  $*${NC}"; echo -e "${GREEN}==============================${NC}"; }

# ---------------------------------------------------------------------------
# 0. Must run as root (or via sudo)
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
  error "Please run as root: sudo $0"
fi

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
APP_DIR="/opt/pumpfun"
REPO_URL="${REPO_URL:-https://github.com/Ghost69-321/PumpFun.git}"
NGINX_CONF_DEST="/etc/nginx/sites-available/pumpfun"
NGINX_ENABLED="/etc/nginx/sites-enabled/pumpfun"
SYSTEMD_SERVICE="/etc/systemd/system/pumpfun.service"

section "Step 1 — Install dependencies"

apt-get update -qq

# ---- Docker ----
if ! command -v docker &>/dev/null; then
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
else
  info "Docker already installed: $(docker --version)"
fi

# ---- Docker Compose (v2 plugin) ----
if ! docker compose version &>/dev/null; then
  info "Installing Docker Compose plugin..."
  apt-get install -y -qq docker-compose-plugin
else
  info "Docker Compose already installed: $(docker compose version)"
fi

# ---- Nginx ----
if ! command -v nginx &>/dev/null; then
  info "Installing Nginx..."
  apt-get install -y -qq nginx
  systemctl enable nginx
else
  info "Nginx already installed: $(nginx -v 2>&1)"
fi

# ---- Certbot ----
if ! command -v certbot &>/dev/null; then
  info "Installing Certbot..."
  apt-get install -y -qq certbot python3-certbot-nginx
else
  info "Certbot already installed: $(certbot --version)"
fi

# ---- Other utilities ----
apt-get install -y -qq git curl ufw

section "Step 2 — Clone / update repository"

if [[ -d "${APP_DIR}/.git" ]]; then
  info "Repo already cloned — pulling latest changes..."
  git -C "${APP_DIR}" fetch origin main
  git -C "${APP_DIR}" reset --hard origin/main
else
  info "Cloning repository to ${APP_DIR}..."
  git clone "${REPO_URL}" "${APP_DIR}"
fi

cd "${APP_DIR}"

section "Step 3 — Configure environment variables"

ENV_FILE="${APP_DIR}/.env.production"

if [[ -f "${ENV_FILE}" ]]; then
  warn ".env.production already exists — skipping interactive setup."
  warn "Edit ${ENV_FILE} manually if you need to change any values."
else
  info "Prompting for required environment variables..."
  echo "(Press Enter to keep the default shown in brackets.)"
  echo ""

  read -rp "Domain (e.g. pumpfun.example.com): " DOMAIN
  [[ -z "${DOMAIN}" ]] && error "Domain is required."

  read -rp "PostgreSQL password [CHANGE_ME_STRONG_PASSWORD]: " POSTGRES_PASSWORD
  POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-CHANGE_ME_STRONG_PASSWORD}"

  read -rp "NextAuth secret [auto-generate]: " NEXTAUTH_SECRET
  if [[ -z "${NEXTAUTH_SECRET}" ]]; then
    NEXTAUTH_SECRET="$(openssl rand -base64 32)"
    info "Generated NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}"
  fi

  read -rp "Solana RPC URL (get one from Helius/QuickNode): " SOLANA_RPC_URL
  [[ -z "${SOLANA_RPC_URL}" ]] && warn "Using public RPC — NOT recommended for production."
  SOLANA_RPC_URL="${SOLANA_RPC_URL:-https://api.mainnet-beta.solana.com}"

  cat > "${ENV_FILE}" << ENVEOF
# Generated by deploy.sh on $(date -u)
# ============================================
# PumpFun Production Environment
# ============================================

# Database
DATABASE_URL=postgresql://pumpfun:${POSTGRES_PASSWORD}@db:5432/pumpfun
POSTGRES_USER=pumpfun
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=pumpfun

# NextAuth
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://${DOMAIN}

# Solana — use a dedicated RPC (Helius, QuickNode, Triton)
SOLANA_RPC_URL=${SOLANA_RPC_URL}
NEXT_PUBLIC_SOLANA_RPC_URL=${SOLANA_RPC_URL}
NEXT_PUBLIC_SOLANA_NETWORK=mainnet-beta

# Platform
PLATFORM_WALLET_ADDRESS=CfyjfkdfVchdvtKyPbBxBoScfSUPBVMwnGbYeXBs5uKw
PLATFORM_FEE_PERCENT=1
GRADUATION_THRESHOLD_SOL=85
NEXT_PUBLIC_PLATFORM_FEE_BPS=100

# App
NEXT_PUBLIC_APP_URL=https://${DOMAIN}
UPLOAD_DIR=./public/uploads

# Docker image (CI/CD sets this automatically)
APP_IMAGE=ghcr.io/ghost69-321/pumpfun:latest

# Domain
DOMAIN=${DOMAIN}
ENVEOF

  chmod 600 "${ENV_FILE}"
  info ".env.production written."
fi

# Load variables for use in the rest of the script
# shellcheck source=/dev/null
set -a; source "${ENV_FILE}"; set +a

section "Step 4 — Start Docker containers"

docker compose -f "${APP_DIR}/docker-compose.prod.yml" \
  --env-file "${ENV_FILE}" pull

docker compose -f "${APP_DIR}/docker-compose.prod.yml" \
  --env-file "${ENV_FILE}" up -d --remove-orphans

section "Step 5 — Run database migrations"

info "Waiting for the app container to be healthy..."
RETRIES=12
until docker compose -f "${APP_DIR}/docker-compose.prod.yml" \
    --env-file "${ENV_FILE}" exec -T app \
    npx prisma migrate deploy 2>/dev/null; do
  RETRIES=$((RETRIES - 1))
  [[ ${RETRIES} -le 0 ]] && error "Migrations failed after retries."
  warn "Container not ready yet — retrying in 10s..."
  sleep 10
done
info "Migrations applied."

section "Step 6 — Configure Nginx"

# Substitute domain in the Nginx config template
sed "s/your-domain.com/${DOMAIN}/g" \
  "${APP_DIR}/nginx/pumpfun.conf" > "${NGINX_CONF_DEST}"

# Add the connection-upgrade map to nginx.conf if missing
if ! grep -q 'connection_upgrade' /etc/nginx/nginx.conf; then
  info "Adding connection upgrade map to nginx.conf..."
  sed -i '/http {/a \\n    map $http_upgrade $connection_upgrade {\n        default upgrade;\n        '"''"'      close;\n    }' /etc/nginx/nginx.conf
fi

# Enable the site
ln -sf "${NGINX_CONF_DEST}" "${NGINX_ENABLED}"

# Remove default site if present
rm -f /etc/nginx/sites-enabled/default

nginx -t && systemctl reload nginx
info "Nginx configured."

section "Step 7 — Obtain SSL certificate (Let's Encrypt)"

if [[ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]]; then
  info "Obtaining SSL certificate for ${DOMAIN}..."
  read -rp "Email address for SSL certificate renewal notices: " CERTBOT_EMAIL
  if [[ -z "${CERTBOT_EMAIL}" ]]; then
    warn "No email provided — certificate expiry notices will NOT be sent."
    certbot --nginx -d "${DOMAIN}" \
      --non-interactive --agree-tos \
      --register-unsafely-without-email \
      --redirect
  else
    certbot --nginx -d "${DOMAIN}" \
      --non-interactive --agree-tos \
      -m "${CERTBOT_EMAIL}" \
      --redirect
  fi
else
  info "Certificate already exists — renewing if needed..."
  certbot renew --quiet
fi

section "Step 8 — Systemd service for auto-start"

cat > "${SYSTEMD_SERVICE}" << SVCEOF
[Unit]
Description=PumpFun Docker Compose
Requires=docker.service
After=docker.service network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=/usr/bin/docker compose -f ${APP_DIR}/docker-compose.prod.yml --env-file ${ENV_FILE} up -d --remove-orphans
ExecStop=/usr/bin/docker compose -f ${APP_DIR}/docker-compose.prod.yml --env-file ${ENV_FILE} down
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable pumpfun.service
info "Systemd service enabled."

section "Step 9 — Configure UFW firewall"

ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp   comment "SSH"
ufw allow 80/tcp   comment "HTTP"
ufw allow 443/tcp  comment "HTTPS"
ufw --force enable
info "UFW firewall configured."

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
section "Deployment complete!"
echo ""
echo -e "  ${GREEN}URL:${NC}       https://${DOMAIN}"
echo -e "  ${GREEN}App dir:${NC}   ${APP_DIR}"
echo -e "  ${GREEN}Env file:${NC}  ${ENV_FILE}"
echo ""
echo -e "  Useful commands:"
echo -e "    docker compose -f ${APP_DIR}/docker-compose.prod.yml --env-file ${ENV_FILE} logs -f app"
echo -e "    docker compose -f ${APP_DIR}/docker-compose.prod.yml --env-file ${ENV_FILE} ps"
echo -e "    systemctl status pumpfun"
echo ""
